In [1]:
%load_ext autoreload
%autoreload 2

%matplotlib inline

import numpy as np
import matplotlib.pylab as plt

from matplotlib import rcParams
rcParams['figure.figsize'] = 15,6

from src import data
!date -I

2024-02-03


In [5]:
import h5py

In [10]:
surf = h5py.File('../data/external/rosen_halgren_sc/public_PLoSBio_final/fsaverage_ico7_pial_surf.mat', 'r')

In [16]:
surf['srf/lh/nverts'][:]

array([[163842.]])

In [17]:
annot = h5py.File('../data/external/rosen_halgren_sc/public_PLoSBio_final/HCP-MMP1.0_fsaverage_annot.mat', 'r')

In [32]:
annot['annot/lIdx/lh'][:].squeeze()==42

array([False, False,  True, ..., False, False, False])

Vertices of ROI 42:

In [33]:
surf['srf/lh/vertices'][:][:,  annot['annot/lIdx/lh'][:].squeeze()==42]

array([[ -9.55357552,  -9.44683075,  -9.81554699, ..., -11.05714226,
        -11.19373989, -11.26519012],
       [ -8.21880722,  -0.92710626,  -4.4716506 , ..., -10.49405098,
        -10.81993675, -11.10538483],
       [ 46.25186157,  42.05752182,  43.89614105, ...,  44.77262878,
         44.52265167,  44.28691864]])